[login]
valid_email = "teambooktest@gmail.com"
valid_password = "Test123!"
invalid_email = "teambooktestgmail.com"
invalid_password = "Test321!"

[registerData]
register_email = "test@example.com"
register_password = "Test123!"
firstName = "John"
lastName = "Snow"
companyName = "JS LLC"