[loginPage]
inputEmail = 'input[id=":r0:"]'
inputPassword = 'input[id=":r1:"]'
loginButton = "#login-button"
errorMsg = '.form-error__error-text'
createAccount = '[href="/register"]'


[header]
header = '.row.header'
userMenu = '[id="openUserMenu"]'
headerLogo = "img[alt='header-logo']"
actuals = "a[class='tb__text__light-blue mobile_hidden']"
planning = "//a[normalize-space()='Planning']"
dashboard = "//a[normalize-space()='Dashboard']"
users = "//a[normalize-space()='Users']"
projects = "//a[normalize-space()='Projects']"
help = "//div[@class='mobile_hidden header__help-icon-block']"

[userMenuPage]
logoutBtn = 'li[role="menuitem"]'
organization = "//a[normalize-space()='Organization']"

[registerPage]
inputFirstName = '[id=":r3:"]'
inputLastName = '[id=":r4:"]'
inputRegisterEmail = '[id=":r5:"]'
inputCompanyName = '[id=":r6:"]'
inputRegisterPassword = '#password_field'
agreeCheckbox = "#root > div.App > div > div.register__right-side > div > div:nth-child(4) > div > img"
submitBtn = '#create-account'
skipBtn = "body > div:nth-child(7) > div:nth-child(3) > div:nth-child(1) > div:nth-child(3) > p:nth-child(1)"

[settingPage]
deleteOrganizationLink = "//p[normalize-space()='Delete Organization']"

[deletePage]
deleteBtn = '#deleteAccountButton'
compaanyName = '#name'
deleteAccountBtn = '#deleteAccount'
